### ISSUE TITLE
Same items load with the same key and breaks sorting.

### ISSUE THREAD

**Issue by PypWalters** [10up/block-components#23] opened 2021-05-07 16:38 UTC
**Describe the bug**
The ContentPicker allows you to select the same post twice. But if you do that and reload, the items load with the same key and you get the following error in the console. "Warning: Encountered two children with the same key, `item-32`".

**Steps to Reproduce**

- Add a block using the Content Picker that has `isOrderable` set to true.
- Search for and select the same post twice.
- Save.
- Reload.
- You will see the error in the console. and you will not be able to click and drag to sort the items.

**Expected behavior**
User should not be able to select the same post twice.

**Comment by Sidsector9** [comment] 2021-10-22 06:40
Hi @PypWalters 

I am not able to select the same search item twice with your configuration.
However, I can if I set the `uniqueContentItems` prop to `false`. It's the only way I am able to reproduce the issue.
Can you please confirm if this prop is set as well in your component?

On another note, if we can add the same search item multiple times by design with `uniqueContentItems={ false }`, then I think we should be working on fixing the repeated keys instead?

**Comment by PypWalters** [comment] 2021-10-22 18:33
@Sidsector9 thanks for taking a look! The repeated keys is definitely the bigger issue here. I'm not sure I knew about the uniqueContentItems option at the time of writing the issue, but regardless if you can add the same post multiple times by design, then yes, the keys need to be unique for those duplicate posts.

I mentioned the isOrderable option in the ticket because there also seemed to be implications for re-ordering the list when 2 of the posts were the same. Maybe they also end up sharing an id that is used by the drag and drop re-ordering functionality? I'm no longer working on the project that was using this functionality so it is difficult for me to retest.

**Comment by Sidsector9** [comment] 2021-10-22 18:55
Thanks for prompt response @PypWalters, the details will certainly help a lot.
Addressing the following:
> Maybe they also end up sharing an id that is used by the drag and drop re-ordering functionality?

Yes they do share the same keys. However the drag and drop re-ordering is functioning, maybe it got fixed in the past few months.

I'll assign this to myself and fix next Monday.

**Comment by tlovett1** [comment] 2021-11-08 20:40
I am only able to select duplicate items if I set the `uniqueContentItems` prop to `false`. After doing that I see the error.

**Comment by fabiankaegy** [comment] 2022-02-18 08:58
closing as this was resolved in #61

**Closed as completed by fabiankaegy** 2022-02-18 08:58 UTC
Labels: [Type] Bug, [Component] Content Picker
